pub mod active;
pub mod budget;
pub mod burn_rate;
pub mod config;
pub mod envelope;
pub mod event;
pub mod exfil;
pub mod pii;
pub mod policy;
pub mod pricing;
pub mod provider;
pub mod risk;
pub mod scanner;
pub mod session;
pub mod store;

pub use active::{ActiveSession, ActiveSessionHandle, create_handle, list_active, update_active};
pub use exfil::CredentialTracker;
pub use budget::{BudgetEnforcer, BudgetStatus};
pub use burn_rate::{BurnRateTracker, LoopDetector};
pub use config::VigilConfig;
pub use envelope::{Envelope, TimestampedEvent, SCHEMA_VERSION};
pub use event::Event;
pub use pii::{scan as scan_pii, scan_watchlist, PiiMatch};
pub use policy::{Policy, PolicyAction, PolicyConfig, PolicyDecision, PolicyEngine, PolicyMatcher};
pub use pricing::PricingTable;
pub use risk::{RiskLevel, RiskScore, score_write};
pub use provider::{ProviderKind, cost_usd, detect_provider_from_host};
pub use scanner::{RegexScanner, Scanner, ScannerChain, WatchlistScanner};
pub use session::{Session, SessionSummary};
pub use store::{sessions_dir, SessionMeta, SessionStore};
