pub mod active;
pub mod budget;
pub mod burn_rate;
pub mod injection;
pub mod drift;
pub mod namegen;
pub mod config;
pub mod envelope;
pub mod event;
pub mod exfil;
pub mod notify;
pub mod pii;
pub mod plugin;
pub mod policy;
pub mod pricing;
pub mod provider;
pub mod risk;
pub mod scanner;
pub mod session;
pub mod replay;
pub mod store;

pub use active::{ActiveSession, ActiveSessionHandle, create_handle, list_active, update_active};
pub use exfil::{BashExfilFinding, CredentialTracker, scan_bash_for_exfil};
pub use budget::{BudgetEnforcer, BudgetStatus};
pub use burn_rate::{BurnRateTracker, LoopDetector};
pub use drift::{DriftAlertPayload, DriftConfig, DriftDetector, DriftSignal};
pub use config::{VigilConfig, ReportConfig, WindowConfig};
pub use envelope::{Envelope, TimestampedEvent, SCHEMA_VERSION};
pub use event::Event;
pub use injection::scan_for_injection;
pub use pii::{scan as scan_pii, scan_watchlist, PiiMatch};
pub use policy::{Policy, PolicyAction, PolicyConfig, PolicyDecision, PolicyEngine, PolicyMatcher};
pub use pricing::PricingTable;
pub use risk::{RiskLevel, RiskScore, score_write};
pub use provider::{ProviderKind, cost_usd, detect_provider_from_host, ProviderAdapter, AnthropicAdapter, GeminiAdapter, OpenAiAdapter};
pub use scanner::{RegexScanner, Scanner, ScannerChain, WatchlistScanner};
pub use session::{Session, SessionSummary};
pub use notify::WebhookNotifier;
pub use plugin::{alert, AlertDetail, AlertLabel, PluginContext, PluginDecision, PluginHost, VigilPlugin};
pub use replay::{build_request_key, RequestKey};
pub use store::{sessions_dir, SessionMeta, SessionStore};
