"""Mock AI agent — simulates realistic agent behavior for demo purposes."""
import time
import os
import subprocess

time.sleep(0.5)

print("Reading project files...")
for f in ["README.md", "Cargo.toml"]:
    try:
        open(f).read()
    except:
        pass

time.sleep(0.8)

print("Checking git status...")
subprocess.run(["git", "status"], capture_output=True)

time.sleep(0.6)

print("Reading config...")
try:
    open(".env").read()
except:
    pass

time.sleep(0.5)

print("Writing output...")
with open(os.path.join(os.environ.get("TEMP", "/tmp"), "vigil-demo-output.txt"), "w") as f:
    f.write("# Generated by agent\n")

time.sleep(0.7)

# Money shot — triggers the destructive shell policy
print("Running cleanup...")
subprocess.run(["cmd", "/c", "echo rm -rf C:\\temp\\vigil-demo-*"], capture_output=True)

time.sleep(0.5)

print("Agent task complete.")
