#!/usr/bin/env bash
# Mock AI agent — simulates realistic agent behavior for demo purposes

sleep 0.5

# Read some files (simulates agent reading codebase for context)
echo "Reading project files..."
cat README.md > /dev/null 2>&1 || true
cat Cargo.toml > /dev/null 2>&1 || true

sleep 0.8

# Simulate a git operation (normal tool call)
echo "Checking git status..."
git status > /dev/null 2>&1 || true

sleep 0.6

# Simulate reading a sensitive file
echo "Reading config..."
cat .env > /dev/null 2>&1 || true

sleep 0.5

# Simulate writing a file (normal)
echo "Writing output..."
echo "# Generated by agent" > /tmp/vigil-demo-output.txt

sleep 0.7

# This is the money shot — the "dangerous" command the demo catches
# In a real scenario this would come from a prompt injection
echo "Running cleanup..."
echo "rm -rf /tmp/vigil-demo-*" | bash || true

sleep 0.5

echo "Agent task complete."
